export const hPartner = [
  {
    id: 1,
    img: "/cdn/static/web/Google.svg",
    cWidth: "150",
    cHeight: "30",
    mWidth: "70",
    mHeight: "30",
    fs: "false",
  },
  {
    id: 2,
    img: "/cdn/static/web/Amazon.svg",
    cWidth: "120",
    cHeight: "40",
    mWidth: "124",
    mHeight: "50",
    fs: "false",
  },
  {
    id: 3,
    img: "/cdn/static/web/Microsoft.svg",
    cWidth: "150",
    cHeight: "40",
    mWidth: "120",
    mHeight: "40",
    fs: "false",
  },
  {
    id: 4,
    img: "/cdn/static/web/Flipkart.svg",
    cWidth: "100",
    cHeight: "40",
    mWidth: "100",
    mHeight: "40",
    fs: "false",
  },
  {
    id: 5,
    img: "/cdn/static/web/facebook.svg",
    cWidth: "150",
    cHeight: "40",
    mWidth: "120",
    mHeight: "40",
    fs: "false",
  },
  {
    id: 6,
    img: "/cdn/static/web/TCS.svg",
    cWidth: "120",
    cHeight: "40",
    mWidth: "120",
    mHeight: "40",
    fs: "true",
  },
  {
    id: 7,
    img: "/cdn/static/web/PAYTM_logo.svg",
    cWidth: "140",
    cHeight: "44",
    mWidth: "140",
    mHeight: "44",
    fs: "true",
  },
  {
    id: 8,
    img: "/cdn/static/web/Zoho.svg",
    cWidth: "140",
    cHeight: "48",
    mWidth: "140",
    mHeight: "48",
    fs: "true",
  },
];
export const pPartner = [
  {
    id: 1,
    img: "/cdn/static/web/liquiloans.svg",
    cWidth: "300",
    cHeight: "120",
    mWidth: "90",
    mHeight: "40",
    fs: "false",
  },
  {
    id: 2,
    img: "/cdn/static/web/propelld.svg",
    cWidth: "500",
    cHeight: "200",
    mWidth: "120",
    mHeight: "40",
    fs: "false",
  },
  {
    id: 3,
    img: "/cdn/static/web/zest-logo.svg",
    cWidth: "200",
    cHeight: "58",
    mWidth: "80",
    mHeight: "20",
    fs: "false",
  },
];
