export const jobData = [
  {
    id: 1,
    title: "Graphics Designer",
    open: true,
    location: "Bangalore, Karnataka, India",
    exp: "3 Years",
    category: "Designer",
    salary: "20k-60k/month",
    img: "/cdn/static/web/New-UI/Designer.svg",
    applied: "305",
  },
  {
    id: 2,
    title: "UI/UX Designer",
    open: true,
    location: "Bangalore, Karnataka, India",
    exp: "1 Years",
    category: "Designer",
    salary: "25k-30k/month",
    img: "/cdn/static/web/New-UI/Designer.svg",
    applied: "94",
  },
  {
    id: 3,
    title: "SEO Manager",
    open: false,
    category: "SEO",
    location: "Bangalore, Karnataka, India",
    exp: "5 Years",
    salary: "60k-80k/month",
    img: "/cdn/static/web/New-UI/seo.svg",
    applied: "235",
  },
  {
    id: 4,
    title: "SEO Fresher",
    open: true,
    category: "SEO",
    location: "Bangalore, Karnataka, India",
    exp: "5 Years",
    salary: "10k-25k/month",
    img: "/cdn/static/web/New-UI/seo.svg",
    applied: "117",
  },
  {
    id: 5,
    title: "SEO Blog Writer",
    open: true,
    category: "SEO",
    location: "Bangalore, Karnataka, India",
    exp: "2 Years",
    salary: "20k-25k/month",
    img: "/cdn/static/web/New-UI/seo.svg",
    applied: "67",
  },
  {
    id: 6,
    title: "Full stack Developer",
    open: true,
    category: "Developer",
    location: "Bangalore, Karnataka, India",
    exp: "4.5 Years",
    salary: "90k-95k/month",
    img: "/cdn/static/web/New-UI/Developer.svg",
    applied: "507",
  },
  {
    id: 7,
    title: "Front End Developer",
    open: true,
    category: "Developer",
    location: "Bangalore, Karnataka, India",
    exp: "1 Years",
    salary: "20k-35k/month",
    img: "/cdn/static/web/New-UI/Developer.svg",
    applied: "189",
  },
  {
    id: 8,
    title: "Back End Developer",
    open: true,
    category: "Developer",
    location: "Bangalore, Karnataka, India",
    exp: "2 Years",
    salary: "40k-55k/month",
    img: "/cdn/static/web/New-UI/Developer.svg",
    applied: "98",
  },

  {
    id: 9,
    title: "Mobile Application Developer",
    open: true,
    category: "Developer",
    location: "Bangalore, Karnataka, India",
    exp: "2.5 Years",
    salary: "45k-55k/month",
    img: "/cdn/static/web/New-UI/Developer.svg",
    applied: "147",
  },
  {
    id: 15,
    title: "MERN Developer",
    open: true,
    category: "Developer",
    location: "Bangalore, Karnataka, India",
    exp: "3.5 Years",
    salary: "55k-75k/month",
    img: "/cdn/static/web/New-UI/Developer.svg",
    applied: "378",
  },
  {
    id: 10,
    title: "Content Writer",
    open: true,
    category: "Writer",
    location: "Bangalore, Karnataka, India",
    exp: "2 Years",
    salary: "40k-55k/month",
    img: "/cdn/static/web/New-UI/Writer.svg",
    applied: "98",
  },
  {
    id: 25,
    title: "Blog/Article Writer",
    open: true,
    category: "Writer",
    location: "Bangalore, Karnataka, India",
    exp: "1.5 Years",
    salary: "15k-35k/month",
    img: "/cdn/static/web/New-UI/Writer.svg",
    applied: "234",
  },
  {
    id: 11,
    title: "Sr. Blog/Article Writer",
    open: true,
    category: "Writer",
    location: "Bangalore, Karnataka, India",
    exp: "3.5 Years",
    salary: "35k-45k/month",
    img: "/cdn/static/web/New-UI/Writer.svg",
    applied: "154",
  },
  {
    id: 13,
    title: "SEO Executive",
    open: true,
    category: "SEO",
    location: "Bangalore, Karnataka, India",
    exp: "1.5 Years",
    salary: "25k-35k/month",
    img: "/cdn/static/web/New-UI/seo.svg",
    applied: "45",
  },
  {
    id: 14,
    title: "Product Designer",
    open: true,
    category: "Designer",
    location: "Bangalore, Karnataka, India",
    exp: "5 Years",
    salary: "75k-95k/month",
    img: "/cdn/static/web/New-UI/Designer.svg",
    applied: "25",
  },
  {
    id: 26,
    title: "Office Admin",
    open: true,
    category: "Other",
    location: "Bangalore, Karnataka, India",
    exp: "1 Years",
    salary: "25k-30k/month",
    img: "/cdn/static/web/New-UI/Others.svg",
    applied: "34",
  },
  {
    id: 16,
    title: "Business Development Manager",
    open: true,
    category: "Digital Marketing",
    location: "Bangalore, Karnataka, India",
    exp: "6 Years",
    salary: "45k-80k/month",
    img: "/cdn/static/web/New-UI/D.M..svg",
    applied: "56",
  },
  {
    id: 17,
    title: "Digital Marketing Expert",
    open: false,
    category: "Digital Marketing",
    location: "Bangalore, Karnataka, India",
    exp: "2 Years",
    salary: "18k-30k/month",
    img: "/cdn/static/web/New-UI/D.M..svg",
    applied: "78",
  },
  {
    id: 18,
    title: "Digital Marketing Specialist",
    open: true,
    category: "Digital Marketing",
    location: "Bangalore, Karnataka, India",
    exp: "3 Years",
    salary: "24k-37k/month",
    img: "/cdn/static/web/New-UI/D.M..svg",
    applied: "178",
  },
  {
    id: 19,
    title: "Senior Manager",
    open: true,
    category: "Digital Marketing",
    location: "Bangalore, Karnataka, India",
    exp: "3 Years",
    salary: "44k-77k/month",
    img: "/cdn/static/web/New-UI/D.M..svg",
    applied: "189",
  },
  {
    id: 27,
    title: "Senior Manager",
    open: true,
    category: "Digital Marketing",
    location: "Bangalore, Karnataka, India",
    exp: "3 Years",
    salary: "44k-77k/month",
    img: "/cdn/static/web/New-UI/D.M..svg",
    applied: "189",
  },
  {
    id: 20,
    title: "Account Executive",
    open: false,
    category: "Accountant",
    location: "Bangalore, Karnataka, India",
    exp: "2 Years",
    salary: "14k-25k/month",
    img: "/cdn/static/web/New-UI/Accountant.svg",
    applied: "78",
  },
  {
    id: 21,
    title: "Senior Accountant",
    open: true,
    category: "Accountant",
    location: "Bangalore, Karnataka, India",
    exp: "3 Years",
    salary: "24k-35k/month",
    img: "/cdn/static/web/New-UI/Accountant.svg",
    applied: "378",
  },
  {
    id: 22,
    title: "Sales Manager",
    open: true,
    category: "Sales",
    location: "Bangalore, Karnataka, India",
    exp: "5 Years",
    salary: "44k-55k/month",
    img: "/cdn/static/web/New-UI/Sales.svg",
    applied: "58",
  },
  {
    id: 23,
    title: "Sales Executive",
    open: false,
    category: "Sales",
    location: "Bangalore, Karnataka, India",
    exp: "2 Years",
    salary: "34k-45k/month",
    img: "/cdn/static/web/New-UI/Sales.svg",
    applied: "148",
  },
  {
    id: 24,
    title: "Inside Sales",
    open: true,
    category: "Sales",
    location: "Bangalore, Karnataka, India",
    exp: "1.5 Years",
    salary: "24k-35k/month",
    img: "/cdn/static/web/New-UI/Sales.svg",
    applied: "128",
  },
];
