#!/usr/bin/env bash
# One-shot deploy for skillslash.com on a fresh Ubuntu EC2 instance:
# Docker + Postgres (as a container, via docker-compose.yml) + the app
# itself, nginx as the public reverse proxy, Let's Encrypt SSL via certbot,
# schema migration, and one admin login seeded.
#
# Usage (run as root, e.g. via `sudo -E ./deploy/ec2-deploy.sh`, from
# inside a checkout of this repo):
#
#   DOMAIN=skillslash.com \
#   LETSENCRYPT_EMAIL=you@skillslash.com \
#   ADMIN_EMAIL=admin@skillslash.com \
#   ADMIN_PASSWORD='a real generated password, not this text' \
#   ./deploy/ec2-deploy.sh
#
# Safe to re-run: every step is idempotent (apt installs, `docker compose
# up -d`, `db:migrate`, `db:create-admin` all no-op or update-in-place on a
# second run rather than failing or duplicating anything).
set -euo pipefail

# ---------------------------------------------------------------- config --
DOMAIN="${DOMAIN:-skillslash.com}"
WWW_DOMAIN="www.${DOMAIN}"
LETSENCRYPT_EMAIL="${LETSENCRYPT_EMAIL:-}"
ADMIN_EMAIL="${ADMIN_EMAIL:-}"
ADMIN_PASSWORD="${ADMIN_PASSWORD:-}"
ADMIN_NAME="${ADMIN_NAME:-Skillslash Admin}"
APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${APP_DIR}/.env"

log()  { printf '\n\033[1;34m==>\033[0m %s\n' "$1"; }
warn() { printf '\033[1;33m!!\033[0m %s\n' "$1"; }
die()  { printf '\033[1;31mERROR:\033[0m %s\n' "$1" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "Run this as root (sudo -E ./deploy/ec2-deploy.sh)."
[ -n "$ADMIN_EMAIL" ] || die "Set ADMIN_EMAIL (the login you'll use at /admin/login)."
[ -n "$ADMIN_PASSWORD" ] || die "Set ADMIN_PASSWORD (at least 10 characters, your own choice - never a default this script would make up)."
[ ${#ADMIN_PASSWORD} -ge 10 ] || die "ADMIN_PASSWORD must be at least 10 characters."
[ -n "$LETSENCRYPT_EMAIL" ] || die "Set LETSENCRYPT_EMAIL (certbot needs it for expiry notices)."
command -v docker >/dev/null 2>&1 || true # installed below if missing

# ---------------------------------------------------------- system deps --
log "Installing system packages (docker, nginx, certbot)..."
apt-get update -y
apt-get install -y ca-certificates curl gnupg nginx git ufw

if ! command -v docker >/dev/null 2>&1; then
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  chmod a+r /etc/apt/keyrings/docker.asc
  . /etc/os-release
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu ${VERSION_CODENAME} stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get update -y
  apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  systemctl enable --now docker
fi

apt-get install -y python3-certbot-nginx

# Firewall: SSH + HTTP + HTTPS only. Postgres and the app port are never
# exposed publicly (docker-compose binds them to 127.0.0.1 - see
# docker-compose.yml), so this is defense-in-depth, not the only barrier.
ufw allow OpenSSH >/dev/null 2>&1 || true
ufw allow "Nginx Full" >/dev/null 2>&1 || true
yes | ufw enable >/dev/null 2>&1 || true

# --------------------------------------------------------------- .env ----
log "Preparing ${ENV_FILE}..."
if [ ! -f "$ENV_FILE" ]; then
  POSTGRES_PASSWORD="$(openssl rand -base64 32 | tr -dc 'A-Za-z0-9' | head -c 32)"
  ADMIN_JWT_SECRET="$(openssl rand -base64 48 | tr -dc 'A-Za-z0-9' | head -c 48)"
  cat > "$ENV_FILE" <<EOF
# Generated by deploy/ec2-deploy.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# DATABASE_URL is set here for completeness but docker-compose.yml
# overrides it at container run time with the compose-network address of
# the \`db\` service - the value below is not actually read in that path.
POSTGRES_USER=skillslash
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=skillslash
DATABASE_URL=postgresql://skillslash:${POSTGRES_PASSWORD}@db:5432/skillslash
ADMIN_JWT_SECRET=${ADMIN_JWT_SECRET}
NODE_ENV=production
EOF
  chmod 600 "$ENV_FILE"
  log "Generated a new POSTGRES_PASSWORD and ADMIN_JWT_SECRET into ${ENV_FILE}."
else
  log "${ENV_FILE} already exists - reusing it (delete it first to regenerate secrets)."
fi
set -a; source "$ENV_FILE"; set +a

# ------------------------------------------------------------- nginx -----
log "Installing the pre-SSL nginx vhost for ${DOMAIN}..."
mkdir -p /var/www/certbot
cp "${APP_DIR}/deploy/nginx/skillslash.conf" /etc/nginx/sites-available/skillslash.conf
sed -i "s/skillslash\.com/${DOMAIN}/g; s/www\.${DOMAIN}/${WWW_DOMAIN}/g" /etc/nginx/sites-available/skillslash.conf
ln -sf /etc/nginx/sites-available/skillslash.conf /etc/nginx/sites-enabled/skillslash.conf
rm -f /etc/nginx/sites-enabled/default
nginx -t
systemctl reload nginx || systemctl restart nginx

# --------------------------------------------------------- build + up ----
log "Building images and starting the app + database..."
cd "$APP_DIR"
docker compose build
docker compose up -d db
log "Waiting for Postgres to report healthy..."
for i in $(seq 1 30); do
  status="$(docker compose ps db --format '{{.Health}}' 2>/dev/null || echo starting)"
  [ "$status" = "healthy" ] && break
  sleep 2
done
[ "$status" = "healthy" ] || die "Postgres never became healthy - check: docker compose logs db"

log "Running schema migration (idempotent)..."
docker compose run --rm migrate node scripts/migrate.js

log "Seeding/refreshing the admin login (${ADMIN_EMAIL})..."
docker compose run --rm migrate node scripts/create-admin.js "$ADMIN_EMAIL" "$ADMIN_PASSWORD" "$ADMIN_NAME"

log "Starting the app..."
docker compose up -d web

log "Waiting for the app to answer on 127.0.0.1:3000..."
for i in $(seq 1 30); do
  curl -fsS -o /dev/null http://127.0.0.1:3000/ && break
  sleep 2
done
curl -fsS -o /dev/null http://127.0.0.1:3000/ || die "App did not come up - check: docker compose logs web"

# --------------------------------------------------------------- ssl -----
log "Requesting the SSL certificate for ${DOMAIN} and ${WWW_DOMAIN}..."
certbot --nginx \
  -d "$DOMAIN" -d "$WWW_DOMAIN" \
  --non-interactive --agree-tos --redirect \
  -m "$LETSENCRYPT_EMAIL"
# certbot's systemd timer (installed with the package) renews automatically
# and reloads nginx on renewal - nothing further to schedule here.
systemctl enable --now certbot.timer >/dev/null 2>&1 || true

nginx -t && systemctl reload nginx

log "Done."
cat <<SUMMARY

  https://${DOMAIN} is live, proxied by nginx to the app container on
  127.0.0.1:3000, with a Let's Encrypt certificate that renews itself.

  Admin login:  https://${DOMAIN}/admin/login
    email:      ${ADMIN_EMAIL}
    password:   (what you set ADMIN_PASSWORD to - not repeated here)

  Useful commands, from ${APP_DIR}:
    docker compose logs -f web          # app logs
    docker compose logs -f db           # Postgres logs
    docker compose restart web          # after pulling new code + rebuild
    docker compose run --rm migrate node scripts/migrate.js   # re-run migrations

  To deploy new code: git pull, then
    docker compose build web && docker compose up -d web

SUMMARY
