export const FsAlumni = [
  {
    id: 1,
    pImg: "/cdn/static/web/GIRISH_BALLAMPALLI.svg",
    pWidth: "85",
    pHeight: "85",
    position: "Software Developer",
    cImg: "/cdn/static/web/New-UI/tessellation-logo.svg",
    cWidth: "30",
    cHeight: "30",
  },
  {
    id: 2,
    pImg: "/cdn/static/web/Ankur_Singh.svg",
    pWidth: "85",
    pHeight: "85",
    position: "Software Engineer",
    cImg: "/cdn/static/web/New-UI/Nike-s.svg",
    cWidth: "95",
    cHeight: "27",
  },
  {
    id: 3,
    pImg: "/cdn/static/web/Anurag_Sinha.svg",
    pWidth: "85",
    pHeight: "85",
    position: "Software Engineer",
    cImg: "/cdn/static/web/New-UI/pega-logo.svg",
    cWidth: "100",
    cHeight: "27",
  },
  {
    id: 4,
    pImg: "/cdn/static/web/Muralikrishna_Alichetty.svg",
    pWidth: "85",
    pHeight: "85",
    position: "Database Consultant",
    cImg: "/cdn/static/web/New-UI/itician.svg",
    cWidth: "100",
    cHeight: "28",
  },
];
export const webAlumni = [
  {
    id: 1,
    pImg: "/cdn/static/web/Muralikrishna_Alichetty.svg",
    pWidth: "85",
    pHeight: "85",
    position: "Database Consultant",
    cImg: "/cdn/static/web/New-UI/itician.svg",
    cWidth: "100",
    cHeight: "28",
  },
  {
    id: 2,
    pImg: "/cdn/static/web/New-UI/suresh-kumar-alumi-web.svg",
    pWidth: "85",
    pHeight: "85",
    position: "Dot Net Developer",
    cImg: "/cdn/static/web/New-UI/infinte.svg",
    cWidth: "50",
    cHeight: "49",
  },
  {
    id: 3,
    pImg: "/cdn/static/web/Manisha_singh.svg",
    pWidth: "85",
    pHeight: "85",
    position: "Sr. Software Engineer",
    cImg: "/cdn/static/web/New-UI/tcs-lgo.svg",
    cWidth: "90",
    cHeight: "36",
  },
  {
    id: 4,
    pImg: "/cdn/static/web/PANKAJ_CHOWDHURY.svg",
    pWidth: "85",
    pHeight: "85",
    position: "Senior Analyst",
    cImg: "/cdn/static/web/New-UI/IBM.svg",
    cWidth: "80",
    cHeight: "32",
  },
];
export const dsAlumni = [
  {
    id: 1,
    pImg: "/cdn/static/web/New-UI/akarsh-srivastava-big.svg",
    pWidth: "85",
    pHeight: "85",
    position: "Data Analyst",
    cImg: "/cdn/static/web/New-UI/trueblue-big.svg",
    cWidth: "135",
    cHeight: "38",
  },
  {
    id: 2,
    pImg: "/cdn/static/web/New-UI/rishabh-jaiswal-icon-big.svg",
    pWidth: "85",
    pHeight: "85",
    position: "Credit Risk Analyst",
    cImg: "/cdn/static/web/New-UI/dvara.svg",
    cWidth: "80",
    cHeight: "58",
  },
  {
    id: 3,
    pImg: "/cdn/static/web/New-UI/Madhuparana.svg",
    pWidth: "85",
    pHeight: "85",
    position: "Data Scientist",
    cImg: "/cdn/static/web/New-UI/tech-mahindra-big.svg",
    cWidth: "130",
    cHeight: "38",
  },
  {
    id: 4,
    pImg: "/cdn/static/web/New-UI/pragyan-prakash-big.svg",
    pWidth: "85",
    pHeight: "85",
    position: "Data Scientist",
    cImg: "/cdn/static/web/New-UI/Accenture-big.svg",
    cWidth: "130",
    cHeight: "39",
  },
];
