// Parses a specially-formatted Markdown (.md) file into a partial CMS post
// object - the Markdown sibling of lib/docxImport.js, sharing its section-
// parsing logic (lib/htmlSectionExtractor.js) and its heading/table
// conventions (lib/contentSectionLabels.js) so "FAQs" and "Courses
// Compared" are recognized identically across every import path. Pairs
// with public/templates/blog-import-template.md (generated by
// scripts/generate-md-template.js). Author, content type, category and
// every image stay untouched - deliberately left out of the template and
// never returned here, same as the Word importer.
import matter from "gray-matter";
import { marked } from "marked";
import * as cheerio from "cheerio";
import { extractSections } from "./htmlSectionExtractor";

const FIELD_KEY_MAP = {
  title: "title",
  slug: "slug",
  excerpt: "excerpt",
  metaTitle: "metaTitle",
  metaDescription: "metaDescription",
  canonicalUrl: "canonicalUrl",
  focusKeyword: "focusKeyword",
  keywords: "keywords",
  ogTitle: "ogTitle",
  ogDescription: "ogDescription",
};

function norm(s) {
  return (s || "").toString().replace(/\s+/g, " ").trim();
}

function slugify(cell) {
  return cell
    .replace(/[^a-z0-9]+/gi, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase();
}

export async function parseMdToPost(text) {
  const warnings = [];
  const { data: frontMatter, content: markdownBody } = matter(text);

  const post = {};
  for (const [rawKey, mappedKey] of Object.entries(FIELD_KEY_MAP)) {
    const raw = frontMatter[rawKey];
    if (raw === undefined || raw === null) continue;
    const value = norm(String(raw));
    if (mappedKey === "keywords") {
      post.keywords = value ? value.split(",").map((w) => w.trim()).filter(Boolean) : [];
    } else if (mappedKey === "slug") {
      post.slug = value ? slugify(value) : "";
    } else {
      post[mappedKey] = value;
    }
  }
  if (Object.keys(frontMatter).length === 0) {
    warnings.push("No front matter found (--- title: ... --- block at the top of the file) - see the sample template for the expected layout.");
  }

  // Images are inserted manually in the editor, never carried over from the
  // file - an image reference here would otherwise become a broken <img
  // src="local/path.png"> once the file itself is gone.
  const strippedImages = /!\[[^\]]*\]\([^)]*\)/.test(markdownBody);
  const cleanedMarkdown = markdownBody.replace(/!\[[^\]]*\]\([^)]*\)/g, "");
  if (strippedImages) {
    warnings.push("Inline images in the document were skipped - add them manually via the editor's image button.");
  }

  const html = marked.parse(cleanedMarkdown, { gfm: true });
  const $ = cheerio.load(html);
  const children = $("body").children().toArray();
  if (!children.length) {
    warnings.push('No "Key Takeaways" / "FAQs" / "Courses Compared" / "Body" headings found - see the sample template for the expected layout.');
  }

  Object.assign(post, extractSections($, children, warnings));

  return { post, warnings };
}
